### ISSUE TITLE
Caching the app database to improve loading times

### ISSUE THREAD

**Issue by bucanero** [Rinnegatamante/VitaDB-Downloader#26]
As mentioned on Discord;

every time I open vitaDB, VitaDB downloads the app database (about 800Kb), even if I close the app and re-open it 2 minutes later.
Perhaps this app database could be cached for a few hours, to improve loading times?

**Comment by Rinnegatamante** [comment]
Not a fan of caching since it would create issues if an update to an homebrew happened few minutes ago and the download is pretty small starting with.

I've added however a way to skip redownloading the database by holding R at boot: https://github.com/Rinnegatamante/VitaDB-Downloader/commit/7044e1978b01d5b002beb7a52e0823355cfab71f
