### ISSUE TITLE
Always states kubridge.skprx  is outdated

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/VitaDB-Downloader#30]
What's the latest version?

Where is it from?

It says it can download and restart console, so I do that, and it complains again.

Thanks!

**Comment by Sarkie** [comment]
Nope, and the file is updated, I can see the update date as yesterday.

Just in ur0

**Comment by Sarkie** [comment]
Want me to upload the .cfg?

How is it checking the date? via md5 or similar?

**Comment by Rinnegatamante** [comment]
via checksum of the skprx against the cheskum on VitaDB.
First it checks where it is (assuming you don't have it in both ur0 and ux0: https://github.com/Rinnegatamante/VitaDB-Downloader/blob/main/source/main.cpp#L1319-L1321
Then checksums it: https://github.com/Rinnegatamante/VitaDB-Downloader/blob/main/source/main.cpp#L1995-L1997
Then queries VitaDB for its hash: https://github.com/Rinnegatamante/VitaDB-Downloader/blob/176d6af9997bc611f82b5d3e775504a6d97de393/source/main.cpp#L1998
And if it detects hash discrepancy, asks for update: https://github.com/Rinnegatamante/VitaDB-Downloader/blob/176d6af9997bc611f82b5d3e775504a6d97de393/source/main.cpp#L1999-L2003

**Comment by Sarkie** [comment]
Ok let get the one off disk and compare the hash to see what's going on

**Comment by Sarkie** [comment]
I have no idea.

I downloaded the file and then compared it to
https://github.com/bythos14/kubridge/releases

Both have MD5 of 
30841f4e8f4ee0ed27e70a4c79c7c695

But if I check
https://vitadb.rinnegatamante.it/get_hb_hash.php?id=611

That returns
d41d8cd98f00b204e9800998ecf8427e

Is that meant to be MD5?

**Comment by Rinnegatamante** [comment]
Seems like it's an issue with VitaDB host. They silently updated something in PHP installation which makes all file reads fail now. I'll look into it.

**Comment by Rinnegatamante** [comment]
Should be fixed now.

**Comment by Sarkie** [comment]
LGTM .

How come I was the only person complaining about this?

**Comment by pmsobrado** [comment]
Forgive me if I say something stupid, but, since some apps share it's ID, could you implement something like this?
1 - Get installed app ID
2 - Check that ID on VitaDB (it may be one, or it may be more than one)
3 - Get all VitaDB checksums for that ID
4 - Compare against local installed app
5 - If one of them matches, the app must be updated, because, as I see it, if more than one app has the same ID on VitaDB it is because of the author giving it that ID, and that can be the only case, since I guess VitaDB doesn't have more than one latest version per app.

Why not compare the version number? Maybe that info isn't given? Or build/modified date or something like that?

Also, I have detected some outdated apps on VitaDB, where can I report this so the database can be updated?

Thanks.

**Comment by Rinnegatamante** [comment]
"5 - If one of them matches, the app must be updated, because, as I see it, if more than one app has the same ID on VitaDB it is because of the different authors giving it that ID, and that can be the only case, since I guess VitaDB doesn't have more than one latest version per app."

That's not the case since apps can have both a nightly and a stable release both on VitaDB.

**Comment by pmsobrado** [comment]
That's a shame. Further implementations could be done, like flagging apps as nightly and such, giving the user the option... but never mind. What about my other question, regarding where can I report outdated apps on VitaDB database?

Thanks!

**Comment by pmsobrado** [comment]
By the way, would be hard to implement a blacklist for homebrew, so the ones that have the outdated issues or the same titleid issues can be skipped?

Thanks.

**Comment by Rinnegatamante** [comment]
The daemon already has a blacklist. As for the app, there are themes which have the Outdated tag fully transparent (so hidden).
