### ISSUE TITLE
Crash while updating an application devilutionX (C2-12828-1)

### ISSUE THREAD

**Issue by DvaMishkiLapa** [Rinnegatamante/VitaDB-Downloader#42]
I get the recurring error of updating [devilutionX](https://github.com/diasurgical/devilutionX/releases/tag/1.5.0) to the latest current version. The error is always the same.
I'll send a dump and a screenshot (it looks weird -_-), maybe it will help something.

My configuration:
FW 3.65, [Enso_ex](https://github.com/SKGleba/enso_ex)
I am using the latest version [VitaDB-Downloader v1.7](https://github.com/Rinnegatamante/VitaDB-Downloader/releases/tag/v.1.7).

[Error Dump](https://github.com/Rinnegatamante/VitaDB-Downloader/files/11966852/psp2core-1688536045-0x00006f4133-eboot.bin.psp2dmp.zip)
[TAI config.txt](https://github.com/Rinnegatamante/VitaDB-Downloader/files/11966859/config.txt)

![Error screenshot](https://github.com/Rinnegatamante/VitaDB-Downloader/assets/18528109/bd2db13a-1764-4281-8367-cca40d915708)

**Comment by Cimmerian-Iter** [comment]
The config txt looks horrible.

You use both repatch and fdfix when it has been advised not to have both of them installed at the same time

ur0:tai/CpuAffinityChanger.skprx Might be a potential suspect

you use ur0:tai/jav.suprx, but still keep noavls plugin this is not normal.

I can continue the list of things wrong, but that's not the point. STOP INSTALLING WHATEVER YOU FIND IN AUTOPLUGIN 2


So now, i will send you a clean config txt that you will use which only have the necessary plugin, and see if the problem is still there. IF not then continue using the config but then ONLY INSTALL PLUGINS YOU ACTUALLY USE. I'm sure if I take one plugin of the list and ask you if you use it the answer will be no.

[config.txt](https://github.com/Rinnegatamante/VitaDB-Downloader/files/11968293/config.txt)

**Comment by DvaMishkiLapa** [comment]
> The config txt looks horrible.

I thank you for your comments about config.txt :D
Honestly, it sounds common sense, I'm glad someone can explain some things to me about it.

I will try this config and check the problem again.

**Comment by DvaMishkiLapa** [comment]
> So now, i will send you a clean config txt

Alas, the error did not go anywhere with this config.
For the sake of interest I also built the program from the last commit, the problem did not go away (which is not surprising, there are not many significant changes).

**Comment by Rinnegatamante** [comment]
Does the error happen solely with devilutionX?

**Comment by DvaMishkiLapa** [comment]
> Does the error happen solely with devilutionX?

I think so. I uninstalled my versions of [Vitapad](https://github.com/carlelieser/vitapad) and [RetroArch](https://www.cfwaifu.com/retroarch-ps-vita/), put in the outdated VPK and tried updating. There were no errors.

**Comment by Rinnegatamante** [comment]
Is this still a thing?

**Comment by DvaMishkiLapa** [comment]
No, the problem is not present in the latest update.
